apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: library-config

          env:
            - name: REACT_APP_BOOK_API_URL
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: BOOK_SERVICE_URL

            - name: REACT_APP_ORDER_API_URL
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: ORDER_SERVICE_URL