apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: order-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_DSN
              value: host=postgres user=postgres password=postgres dbname=orders port=5432 sslmode=disable

            - name: BOOK_SERVICE_URL
              value: http://book-api:8000