name: Deploy

on:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Apply ConfigMap
        run: |
          kubectl apply -f k8s/configmap.yaml

      - name: Create Secrets
        run: |
          kubectl create secret generic library-secrets \
            --from-literal=MYSQL_USER=${{ secrets.MYSQL_USER }} \
            --from-literal=MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            --from-literal=POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --from-literal=POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy
        run: |
          kubectl apply -f k8s/

      - name: Rolling updates
        run: |
          kubectl rollout status deployment/book-api
          kubectl rollout status deployment/order-api
          kubectl rollout status deployment/frontend